spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bayzdelivery?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Rohit@1897
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    rest:
      base-path: /api
